// frontapp/src/routes/header.svelte
<script>
	import { onMount } from 'svelte';
	import { isLogin } from '$lib/login_stores.js';
	import { logout } from './member/login_check.js';
	import { toastNotice } from './app.js';

	async function logoutProcess() {
		await logout();
		toastNotice('로그아웃 되었습니다.');
	}

	onMount(() => {
		$isLogin = !!localStorage.getItem('nickname');
	});
</script>

<div class="navbar bg-base-100">
	<div class="navbar-start">
		<div class="dropdown">
			<div tabindex="-1" role="button" class="btn btn-ghost btn-circle">
				<i class="fa-solid fa-bars"></i>
			</div>
			<ul
				tabindex="0"
				class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52"
			>
				<li><a href="/article"> <i class="fa-solid fa-rectangle-list"></i>글 목록</a></li>
				{#if $isLogin}
					<li>
						<a class="nav-link" href="/member/mypage">
							<i class="fa-solid fa-address-card"></i> 마이페이지</a
						>
					</li>
					<li>
						<a class="nav-link" on:click={logoutProcess}>
							<i class="fa-solid fa-door-closed"></i>로그아웃</a
						>
					</li>
				{:else}
					<li>
						<a class="nav-link" href="/member/signup">
							<i class="fa-solid fa-user-plus"></i> 회원가입</a
						>
					</li>
					<li>
						<a class="nav-link" href="/member/login">
							<i class="fa-solid fa-door-open"></i> 로그인</a
						>
					</li>
				{/if}
			</ul>
		</div>
	</div>
	<div class="navbar-center">
		<a class="btn btn-ghost text-xl" href="/">Img_Forest</a>
	</div>
	<div class="navbar-end flex items-center">
		<div tabindex="-1" role="button" class="btn btn-ghost btn-circle">
			<i class="fa-solid fa-magnifying-glass"></i>
		</div>
	</div>

</div>

// react_front/src/components/layouts/Header.js
import '../../App.css';
import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useState, useEffect } from 'react';
import { toastNotice } from '../ToastrConfig';


const apiUrl = process.env.REACT_APP_CORE_API_BASE_URL;
const frontUrl = process.env.REACT_APP_CORE_FRONT_BASE_URL;
const Navbar = () => {
    const [isLogin, setIsLogin] = useState(false);
  
    useEffect(() => {
      setIsLogin(!!localStorage.getItem('nickname'));
    }, []);
  
    const logoutProcess = async () => {
      await logout();
      toastNotice('로그아웃 되었습니다.')}; 

return (
    <div className="navbar bg-base-100">
      <div className="navbar-start">
        <div className="dropdown">
          <div tabIndex="-1" role="button" className="btn btn-ghost btn-circle">
            <FontAwesomeIcon icon={faBars} />
          </div>
          <ul tabIndex="0" className="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
            <li><Link to="${frontUrl}/article"><FontAwesomeIcon icon={faRectangleList} /> 글 목록</Link></li>
            {isLogin ? (
              <>
                <li><Link className="nav-link" to="${frontUrl}/member/mypage"><FontAwesomeIcon icon={faAddressCard} /> 마이페이지</Link></li>
                <li><button className="nav-link" onClick={logoutProcess}><FontAwesomeIcon icon={faDoorClosed} />로그아웃</button></li>
              </>
            ) : (
              <>
                <li><Link className="nav-link" to="${frontUrl}/member/signup"><FontAwesomeIcon icon={faUserPlus} /> 회원가입</Link></li>
                <li><Link className="nav-link" to="${frontUrl}/member/login"><FontAwesomeIcon icon={faDoorOpen} /> 로그인</Link></li>
              </>
            )}
          </ul>
        </div>
      </div>
      <div className="navbar-center">
        <Link className="btn btn-ghost text-xl" to="/">Img_Forest</Link>
      </div>
      <div className="navbar-end flex items-center">
        <div tabIndex="-1" role="button" className="btn btn-ghost btn-circle">
          <FontAwesomeIcon icon={faMagnifyingGlass} />
        </div>
      </div>
    </div>
  );
};


export default Header;
